### ISSUE TITLE
500 Internal Error, fordi grenselinjen ble forsøkt endret fra LINESTRING

### ISSUE THREAD

**Issue by larsop** [kartverket/NGIS-OpenAPI#101]
Hei

Her er et bilde av punkene i linjen 34210a03-40cd-43d4-b013-e10d34c6e569 

![ar5_linje_emdret](https://user-images.githubusercontent.com/5681424/199974874-57276085-c0f0-4c12-8d3f-1f7c7650450f.png)

Her er wkt'ene for linjen 34210a03-40cd-43d4-b013-e10d34c6e569 fra feilmedingen

`LINESTRING(624522.20000000007 6748090.8700000001,624528.08999999997 6748087.2699999996,624532.58999999997 6748084.75,624536.47999999998 6748083.2999999998,624531.67000000004 6748079.7199999997,624528.32000000007 6748074.5300000003,624525.48999999999 6748066.9100000001,624523.13 6748056.0800000001,624521.68000000005 6748038.6100000003,624520.60999999999 6748021.6900000004,624519.39000000001 6748002.4699999997,624519.39000000001 6747993.0099999998,624520.54000000004 6747989.3899999997,624523.13 6747986.0300000003) 
`

`LINESTRING(624522.19499999995 6748090.8739999998,624528.08999999997 6748087.2699999996,624532.58999999997 6748084.75,624536.47999999998 6748083.2999999998,624531.67000000004 6748079.7199999997,624528.32000000007 6748074.5300000003,624525.48999999999 6748066.9100000001,624523.13 6748056.0800000001,624521.68000000005 6748038.6100000003,624520.60999999999 6748021.6900000004,624519.39000000001 6748002.4699999997,624519.39000000001 6747993.0099999998,624520.54000000004 6747989.3899999997,624523.13 6747986.034))
`

Ser vi på avstanden mellom første og siste i feilmelding er den på ca 7 mm så feil melding gir mening når man ser på  feilmeldingen.

1) Select st_distance('Point (624522.20000000007 6748090.8700000001)', 'Point (624522.19499999995 6748090.8739999998)');
     st_distance      
----------------------
 0.006403124159763543

2) Select st_distance('Point (624523.13 6747986.0300000003)', 'Point (624523.13 6747986.034)');
     st_distance      
----------------------
 0.003999999724328518
(1 row)

Men når ser vi forskjellien mellom første og siste punkt i det
[ar5_pg_OK_USER_REQUEST_4CB569567DB4AEF705882CECE0114BB4_e8a58dff-c5cc-4692-b5ea-16b50394514d_dataset_baf98b70-29ee-469a-9667-59c2540ddbc2__UTF-8_1667562393436.json.gz](https://github.com/kartverket/NGIS-OpenAPI/files/9938652/ar5_pg_OK_USER_REQUEST_4CB569567DB4AEF705882CECE0114BB4_e8a58dff-c5cc-4692-b5ea-16b50394514d_dataset_baf98b70-29ee-469a-9667-59c2540ddbc2__UTF-8_1667562393436.json.gz)
 vi får  fra NGIS og sender tilbake så er den mye mindre dvs. under en millimeter jeg forstår ikke hvor linjen i feil melding kommer fra. 

```

Select ST_distance('Point(624522.19499999995 6748090.8739999998)', 'Point(624522.1952764351 6748090.87389317)');
      st_distance      
-----------------------
 0.0002963597176692849
(1 row)

Select ST_distance('Point(624523.13 6747986.034)', 'Point(624523.130391164 6747986.03374938)');
      st_distance       
------------------------
 0.00046456383980433976
(1 row)


```

Siden forskjellen er under en millimeter burde ikke dette feilet.

Her er også et bilde som at forskjellen ikke stemmer med feil melding vi får fra NGIS og  sender tilbake 
[ar5_upadteDatasetFeatures_FAIL_UTF-8_1667553424202_.json.gz](https://github.com/kartverket/NGIS-OpenAPI/files/9938822/ar5_upadteDatasetFeatures_FAIL_UTF-8_1667553424202_.json.gz)

<img width="707" alt="Screenshot 2022-11-04 at 14 50 49" src="https://user-images.githubusercontent.com/5681424/199989109-3b8c0722-72c8-473e-beee-bd69622de99a.png">

 

Her er hele feil melding,

`500 Internal Error: "{"detail":"Commit feilet","errors":[{"reason":"Alle objekter som deler geometrien er ikke med i innsjekken:\n\tFlaten (id: 2279480517 globalid: ea80e8fe-5759-4b49-b5d1-2d1f3cd24e71) som ble sjekket inn mangler følgende tilhørende objekter i innsjekken:\n\t\tGrenselinjen (id: 2172175637 globalid: 34210a03-40cd-43d4-b013-e10d34c6e569 fordi grenselinjen ble forsøkt endret fra LINESTRING(624522.20000000007 6748090.8700000001,624528.08999999997 6748087.2699999996,624532.58999999997 6748084.75,624536.47999999998 6748083.2999999998,624531.67000000004 6748079.7199999997,624528.32000000007 6748074.5300000003,624525.48999999999 6748066.9100000001,624523.13 6748056.0800000001,624521.68000000005 6748038.6100000003,624520.60999999999 6748021.6900000004,624519.39000000001 6748002.4699999997,624519.39000000001 6747993.0099999998,624520.54000000004 6747989.3899999997,624523.13 6747986.0300000003) til LINESTRING(624522.19499999995 6748090.8739999998,624528.08999999997 6748087.2699999996,624532.58999999997 6748084.75,624536.47999999998 6748083.2999999998,624531.67000000004 6748079.7199999997,624528.32000000007 6748074.5300000003,624525.48999999999 6748066.9100000001,624523.13 6748056.0800000001,624521.68000000005 6748038.6100000003,624520.60999999999 6748021.6900000004,624519.39000000001 6748002.4699999997,624519.39000000001 6747993.0099999998,624520.54000000004 6747989.3899999997,624523.13 6747986.034))"}],"title":"Commit feilet","type":"http://ngisopenapi.no/errors/commit_error"}"
`

Lars

**Comment by NilsIvarNes** [comment]
Gammel feil i gammel versjon. Lukkes inntil problemet ev. oppstår på nytt i ny versjon
