### ISSUE TITLE
Query-parameter: Filtrere på flere objekttyper

### ISSUE THREAD

**Issue by NilsIvarNes** [kartverket/NGIS-OpenAPI#102]
I dokumentasjonen er det beskrevet filtrering på objekttype:

![image](https://user-images.githubusercontent.com/102019320/200776913-098086f6-d2d1-4dbc-9780-93f3cdbbfadd.png)

Filtrering på en objekttype "query=eq(*,Bygning)" er testet og virker som beskrevet.
 
Når det gjelder filtrering på flere objekttyper "query=in(*,Bygning,AnnenBygning)" så er det antagelig en feil i forklarende tekst i dokumentasjonen (minner om en klassisk "klipp og lim"- feil!?). I tillegg har vi ikke fått denne filtreringen til å virke ved testing, så her er det antagelig noe som bør sjekkes, i hvert fall i dokumentasjonen, men antagelig også i implementasjonen på server.

**Comment by meastp** [comment]
Dette er rettet for en stund siden, bør ligge i Kartverkets prod-miljø.
