### ISSUE TITLE
FKB 5.0 og ny openapi.yaml

### ISSUE THREAD

**Issue by larsop** [kartverket/NGIS-OpenAPI#105]
Hvor finner jeg openapi.yaml for FKB 5.0 slik at jeg kan generere ny klient kode på for java ?

Antar at denne er endret for FKB 5.0 men finner lite info om dette på github.

Det siste jeg finner er dette ?
![Screenshot 2023-02-06 at 13 22 29](https://user-images.githubusercontent.com/5681424/216971226-84f3676a-2622-4762-b9fc-5a43a5c64275.png)

Se også mail sendt for ca 1 uke siden .

**Comment by larsop** [comment]
Kopi av mail sendt 27/01 etter oppstarts måte


```
Tusen takk for møte.

Det ble snakket om dette på møtet også, men kanskje dere legge ut et dokument på https://github.com/kartverket/NGIS-OpenAPI som viser hva er testet mot kartverket sine test servere ?


Jeg antar det skjer endringer openapi.yml etter hvert som det legges ut nye ting eller er det bare på server siden det er ting som må endres ?

Hvis det skjer ting med openap.yml kan dere evt holde develop branchen  eller en annen branch oppdatert slik at den stemmer med det som til enhver tid ligger ute på kartverket sine test servere.

Lars
```

**Comment by larsop** [comment]
Ser siste  releasen er fra https://github.com/kartverket/NGIS-OpenAPI/releases er fra Desember 2019, kanskje man kunne laget en release for FKB 5.0 ?

**Comment by NilsIvarNes** [comment]
Innspill om egen release og ev. egen gren for oppdateringer som kommer i QMS13/FKB5.0 (og nå finnes på test) noteres og vurderes...

Slik jeg forstår det er selve API-et ikke endret (og dermed heller ikke noen ny versjon av yaml-fila). Det som er endret er kun at dataene som sendes over er endret dersom man benytter format versjon 2.0 (og det må man om man skal forholde seg til FKB 5.0 datamodeller). 

Det som foreløpig er gjort er å forsøke å beskrive forskjellene fra "application/vnd.kartverket.sosi+json; version=1.0" til "application/vnd.kartverket.sosi+json; version=2.0" inn i dokumentasjonen her på github hovedgrena, inkl. komplettering og oppdatering av eksempelfiler som viser bruk av versjon 2.0. Norkart jobber med flere eksempler. 

Oppklarende? Noe konkret som mangler eller feiler?

**Comment by Dangeroustuber** [comment]
@larsop Mulig jeg misforstår det du er spør om men den openapi.yaml filen som er i repoet på master branchen nå inneholder alle endringene jeg gjorde så langt i forbindelse med fkb5/qms13. Det som ble lagt til var nye eksempler. Alle endringene kan du se på denne committen: [qms13 commit](https://github.com/kartverket/NGIS-OpenAPI/commit/e5b3b42e52c0f57358d44cf0d75a2645bc1dec43) fra pull request: #100. Det er ikke noe ny fkb5 yaml fil, den som er i master branchen er den som er mest oppdatert.

**Comment by larsop** [comment]
> Oppklarende? Noe konkret som mangler eller feiler?

Ja nå feiler https://openapi-test13.kartverket.no/v1/datasets/datasets med 400 . Jeg for sjekke litt mere.

**Comment by larsop** [comment]
> @larsop Mulig jeg misforstår det du er spør om men den openapi.yaml filen som er i repoet på master branchen nå inneholder alle endringene jeg gjorde så langt i forbindelse med fkb5/qms13. Det som ble lagt til var nye eksempler. Alle endringene kan du se på denne committen: [qms13 commit](https://github.com/kartverket/NGIS-OpenAPI/commit/e5b3b42e52c0f57358d44cf0d75a2645bc1dec43) fra pull request: #100. Det er ikke noe ny fkb5 yaml fil, den som er i master branchen er den som er mest oppdatert.

Takk, den er grei da bruker jeg master.

**Comment by larsop** [comment]
Kankskje man kunne fått lagt https://openapi-test13.kartverket.no/v1/datasets/datasets på https://editor.swagger.io/?url=https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/openapi.yaml, så jeg kan testet det rett fra swagger ?

**Comment by larsop** [comment]
> Oppklarende? Noe konkret som mangler eller feiler?

Da har jeg hentet ned siste yaml fil fra master for en feil som under for bbox "POLYGON ((60.42358717068289 10.048219965180731, 60.42358717068289 10.04841996518073, 60.4237871706829 10.04841996518073, 60.4237871706829 10.048219965180731, 60.42358717068289 10.048219965180731))"


`org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://openapi-test13.kartverket.no/v1/datasets/b3930a04-dfbd-4887-8c02-c744c14f6181/features/b3930a04-dfbd-4887-8c02-c744c14f6181": https://openapi-test13.kartverket.no/v1/datasets/b3930a04-dfbd-4887-8c02-c744c14f6181/features/b3930a04-dfbd-4887-8c02-c744c14f6181?references=none&limit=3&crs_EPSG=4258&normalized_for_visualization=true; nested exception is java.io.FileNotFoundException: https://openapi-test13.kartverket.no/v1/datasets/b3930a04-dfbd-4887-8c02-c744c14f6181/features/b3930a04-dfbd-4887-8c02-c744c14f6181?references=none&limit=3&crs_EPSG=4258&normalized_for_visualization=true
`
Ser dere noe i loggen på server siden  om det er noe feil på klient eller server siden ?

**Comment by larsop** [comment]
Feilen er den samme også med references=all

**Comment by larsop** [comment]
Jeg closer denne og lager enkelt tasker så blir enklere å holde oversikt.
