### ISSUE TITLE
Add https://openapi-test13.kartverket.no/v1 for testing

### ISSUE THREAD

**Issue by larsop** [kartverket/NGIS-OpenAPI#106]
to https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/openapi.yaml

**Comment by Dangeroustuber** [comment]
Har lagt det til i dette draft pull requestet foreløpig: #104. Er dette noe som haster veldig mye så lager jeg nytt pull request og legger det til med en gang. Si ifra hvis det er ønskelig.

**Comment by larsop** [comment]
Den er fin. Det er fint om det fikses så snart som mulig så det blis erklere å teste for andre etter hvert som det legges ut nye fikser
