### ISSUE TITLE
Bruk av branch i git

### ISSUE THREAD

**Issue by larsop** [kartverket/NGIS-OpenAPI#109]
Nå legges alt ut i master branch (som ofte også kalles main) , selv om ting bare ligger på test.

Et problem med er at vi som brukere mister oversikten over hvor ting ligger, f.eks nå ligger det eksempler i master som ikke gjelder prod.

En annen problem med å legge alt  ut på master selv om det ikke er i prod er at hvis man må gjøre em fiks på det ligger i prod kan man ikke gjøre det på master. 

Når man da tillegg ikke releaser blir dette ikke enkelt å holde styr.

Jeg hadde ihvertfall laget  følgende branher
utv - legges på  Norkart sine utv servere
test - legges Kartverket sine test servere
utv_fkb50 - legges på  Norkart sine utv servere
test_fkb50 -  legges Kartverket sine test servere

Når det gjelder master hadde jeg ruller det tilbake slik at det stemmer med det som ligger i prod i dag.

**Comment by NilsIvarNes** [comment]
Dette repoet inneholder jo bare en dokumentasjon av API-et og ikke selve kildekoden så det er ikke noen direkte kobling mellom grener her i git og grener i kodebasen for serverprogramvaren (QMS). Likevel kan det nok godt hende vi kunne/burde bruke grener her i repoet mer aktivt for å gjøre det mer oversiktlig for dere som programmerer mot API-et. To be continued!

**Comment by larsop** [comment]
> Dette repoet inneholder jo bare en dokumentasjon av API-et og ikke selve kildekoden

Her forstår jeg ikke helt hva du mener.

Når jeg bruker API så må jeg generer jeg kilde koden basert på  ymal filen som ligger i dette repoet, så fra klient siden så er dette kilde koden.

Jeg antok at man lagde server siden av api basert på samme yaml fil ohgså for sikre at API blir riktig og at man så plugger server siden bak den auto genererte kode,

**Comment by meastp** [comment]
Vi bruker ikke generator på server-siden. Se oppdatert readme for status hos Karverket. Skal begynne å bruke git tags for å angi hvilken versjon av QMS / Kartverket har som tilsvarer hvilken versjon av openapi-spesifikasjonen.
