### ISSUE TITLE
get features request tar ikke hensyn til parameteren references

### ISSUE THREAD

**Issue by larsop** [kartverket/NGIS-OpenAPI#111]
```
 curl -i \
        -H 'Authorization:????????' \
        -H 'Accept:application/vnd.kartverket.sosi+json version=2.0' \
        -H 'Content-Type:application/vnd.kartverket.sosi+json version=2.0' \
        -H 'X-Client-Product-Version:curls ar5_java_web' \
        "https://openapi-test13.kartverket.no/v1/datasets/b3930a04-dfbd-4887-8c02-c744c14f6181/features?bbox=564771.167355351732112467288970947265625,6681823.152059216983616352081298828125,566278.832644654554314911365509033203125,6682794.7871170379221439361572265625&crs_EPSG=25832&normalized_for_visualization=true&limit=10000&query=eq(*,ArealressursFlate)" \
        -o /tmp/utm_t1.json

```

Jeg for det samme resultatet

    uten references parameteren som over
    med references=all
    med references=none

Jeg har ikke gjort en full sjekk på alle linjer er med ennå. Det vil bli gjort når vi skal lagre den nye strukturen i Postgis Topology basen.

**Comment by NilsIvarNes** [comment]
References brukes for å angi om refererte objekter (flateavgrensninger og antagelig også andre assosierte objekter) skal være med i svaret. Dette er spesielt aktuelt i forbindelse med spørriger på id til objektene.

Her gjør du en spørring på bbox. Da vil alle objekter innenfor bbox bli med uavhengig av om de er referert eller ikke, uten at dette nødvendigvis er en feil. Det vil vel da i så fall gjelde refererte objekter utenfor bbox.

Etter det jeg forstår er det samme logikk/håndtering av dette i ny versjon (QMS13) som i gammel versjon (QMS12). Det må ev. diskuteres nærmere om og ev. hvordan dette skal endres før det gjøres noe...

**Comment by larsop** [comment]
Sorry switching to English because of broken arm and easier voiceover with English. 

In QMS 12 if we did not send with the parameter references like all in the start we then did get polygons that did not have all borders included because some of the borders was outside the bounding box sent in. 

So to secure that we got all borders used by polygons touching the bounding box we had to use references like all

**Comment by NilsIvarNes** [comment]
Regner med denne saken ikke er aktuelle lenger i og med at den ikke er fulgt opp siden februar 2023
