### ISSUE TITLE
Feature request: English documentation

### ISSUE THREAD

**Issue by strk** [kartverket/NGIS-OpenAPI#112]
I'd like to learn more about this API but cannot read Norwegian. Any chance to expose a link to an English version of the specification ?

**Comment by NilsIvarNes** [comment]
We do not have resources to do this on short notice. Sometime i the future perhaps? Are there more of you who want documentation in english?

**Comment by strk** [comment]
I'm specifically interested in https://github.com/kartverket/NGIS-OpenAPI/blob/master/spec/openapi.yaml#L88 for https://gitlab.com/nibioopensource/ar5web_pgtopo_update_sql/-/issues/7
