### ISSUE TITLE
Enkelte AR5 Flater mangler datafangstdato og verifiseringsdato når de lastes ned fra test QMS 13

### ISSUE THREAD

**Issue by larsop** [kartverket/NGIS-OpenAPI#117]
Disse er på påkrevet slik jeg forstår det, men når jeg jeg henter ned data hender det at enkelte flater mangler verdi slik som under.

```

 "properties": {
        "featuretype": "ArealressursFlate",
        "arealtype": "12",
        "treslag": "98",
        "skogbonitet": "98",
        "grunnforhold": "98",
        "datafangstdato": null,
        "verifiseringsdato": null,
        "identifikasjon": {
          "navnerom": "http://data.test.geonorge.no/SFKB/FKB-AR5/so",
          "lokalId": "265c4772-e2ca-4181-a8a5-67a63e46d394",
          "versjonId": "2023-03-07 13:42:38.711601000"
        },
        "oppdateringsdato": "2023-03-07T13:42:38",
        "klassifiseringsmetode": "sOrto",
        "opphav": "samf",
        "registreringsversjon": "2014-03-01",
        "avgrensesAvArealressursGrense": [


```

**Comment by NilsIvarNes** [comment]
Det er definert en del datoer (18000101, 10000101 ++) som tolkes som "ikke angitt" og lagres som <null> ved lagring i NGIS. Ved skriving av data ut igjen med NGIS-API oversettes disse til 18000101 (ref: http://sosi.geonorge.no/Standarder/FKB_generell_del/#truedatafangstdato ), men ved skriving ut til JSON med NGIS-OpenAPI mangler denne oversettelsen. Dette vil bli justert i NGIS-OpenAPI med det første.

(imens anbefales det at <null> oversettes til 18000101 på klienten ved skriving tilbake til server slik at det validerer)

**Comment by larsop** [comment]
Den er grei, da bruker vi 18000101 for  null verdier for disse.

**Comment by larsop** [comment]
Denne skal nå være oppdatert i test systemmet NGIS-OpenApi

**Comment by meastp** [comment]
bekreftet rettet
