### ISSUE TITLE
Spørringer uten "normalized_for_visualization" kan gi flere versjoner av samme objekt

### ISSUE THREAD

**Issue by jarped** [kartverket/NGIS-OpenAPI#121]
Flere versjoner av samme objekt hvis spørring mangler parameter "normalized_for_visualization".

Her har jeg først opprettet en flate med avgrensning og sendt den inn. Deretter henter jeg den ut igjen, splitter avgrensningen og sender inn igjen. Når jeg så skal hente den ut på ny kommer begge versjonene av avgrensninga.

Feilende spørring:
https://openapi-test13.kartverket.no/v1/datasets/798aed3a-411b-48f9-9839-175ae2c07919/features?locking_type=user_lock&bbox=611888.94,6564526.5,611965.25,6564593.5&crs_EPSG=5972&references=none

Feature med lokalId '1cc53e3d-0127-448a-8af5-66f9c2a07f95' kommer to ganger.

Spørringen fungerer hvis vi legger på enten normalized_for_visualization=false eller normalized_for_visualization=true.

Her er svarene jeg får på de to forskjellige spørringene:
[responses.zip](https://github.com/kartverket/NGIS-OpenAPI/files/11421051/responses.zip)

**Comment by meastp** [comment]
@jarped Har du navnet på dataset også, for å gjøre det enklere å forsøke å gjenskape samme feil? :)

**Comment by Dangeroustuber** [comment]
@jarped Vi har ikke klart å gjenskape denne. Vi har gjort det samme som du har beskrevet ovenfor men vi får ut riktig data, flaten og 2 avgrensingslinjer. Parameteret har ingen påvikring på antallet objekter som kommer ut i responsen i vårt tilfelle. 

Vi må ha mer informasjon om hver spørring som blir gjort. Hva er det du sender inn etter å ha splittet avgrensningen?

**Comment by NilsIvarNes** [comment]
Regner med denne ikke er et problem i og med at den ikke er fulgt opp videre og lukker saken
