### ISSUE TITLE
Mismatch cardinality between XSD and API

### ISSUE THREAD

**Issue by andreasbaa** [kartverket/NGIS-OpenAPI#125]
Se havnedata, eksempelvis **Forbudsområde**, egenskap **gjelderForFartøytype**

I følge objektkatalogen er denne 1 til mange (1,n).
![image](https://github.com/kartverket/NGIS-OpenAPI/assets/10812849/0ad6d7e1-0ca9-4200-8677-54da200d981e)
Dette samsvarer også med UML-modell: 
![image](https://github.com/kartverket/NGIS-OpenAPI/assets/10812849/0daf8541-69bc-4181-a078-7ea10897cb2d)
Samsvarer også med XSD:
![image](https://github.com/kartverket/NGIS-OpenAPI/assets/10812849/fea52332-902e-4ac8-a76f-c7fd3f1b8c9a)

Men data som vi får ut fra NGIS-OpenAPI kommer ut som om kardinaliteten var (1,1).
![image](https://github.com/kartverket/NGIS-OpenAPI/assets/10812849/83769185-a751-486d-8094-f962b5974861)

Også Json-skjemaet indikerer (1,1):
![image](https://github.com/kartverket/NGIS-OpenAPI/assets/10812849/fa520769-4200-493b-91ff-a4ab4a2da2a5)

@NilsIvarNes @larseggan @meastp

**Comment by larseggan** [comment]
JSON schema skal vel ha anyOf og ikke oneOf for multiple egenskaper.

**Comment by NilsIvarNes** [comment]
Det er funnet en feil ved import av objektkataloger med listeegenskaper i QMS13 som gir denne feilen. I og med at det ikke finnes slike modellelementer i FKB 5.0 har dette desverre ikke blitt oppdaget tidligere. Dette vil bli retta opp så fort riktig utvikler er tilbake fra ferie.

**Comment by larseggan** [comment]
@NilsIvarNes Er dette rettet nå?

**Comment by meastp** [comment]
Den er rettet i QMS 13.0.7

**Comment by NilsIvarNes** [comment]
Takk, @meastp ! Til @larseggan : QMS 13.0.7 er nå lagt inn i Kartverkets testbaser. Mulig vi må gjøre en ny import av objektkatalog for Havnedata 3.0 for at dette skal blir riktig ut gjennom API-et for dette datasettet.
