### ISSUE TITLE
Gå gjennom required properties for Dataset

### ISSUE THREAD

**Issue by jarped** [kartverket/NGIS-OpenAPI#34]
Endringene i https://github.com/kartverket/SFKB-API/pull/33/commits/ea887be19b35d5689e144831dba2bb718fd8c609 ble gjort på basis av at det var disse properties som ble levert av /Datasets. Vi må avklare om de er i orden for videre bruk. Merget i #33

**Comment by jarped** [comment]
Forselår forøvrig at vi legger til namespace. Dette vil i kombinasjon med epsg gi oss mulighet til å mappe en vilkårlig gml-feature direkte til korrekt Dataset i de tilfellene det bare er ett dataset pr kombinasjon epsg/namespace.

**Comment by meastp** [comment]
Jeg har lagt inn det som er reelt i dagens versjon i #50
