### ISSUE TITLE
Operasjoner som endrer/oppretter features tar lang tid

### ISSUE THREAD

**Issue by jarped** [kartverket/NGIS-OpenAPI#37]
### Klient-kode:
Insert took 00:00:34.1857038
Delete took 00:00:34.2805077
Replace took 00:00:34.7176964

### Postman:
Insert brukt i Postman:
[tmp2B46.txt](https://github.com/kartverket/SFKB-API/files/3917380/tmp2B46.txt)

Resultat:
![image](https://user-images.githubusercontent.com/3570752/70064805-69378c00-15ea-11ea-9939-75e806f23f8b.png)

**Comment by jarped** [comment]
Denne eksisterer fortsatt

**Comment by NilsIvarNes** [comment]
Gammel feil og mye er endret/utbedret i løsningen. Lukkes inntil dette ev. blir en utfordring på nytt.
