### ISSUE TITLE
Autogenerert klientkode lager feil boundingbox

### ISSUE THREAD

**Issue by jarped** [kartverket/NGIS-OpenAPI#43]
Autogenerert kode klarer ikke få med seg reglene for serialisering av BoundingBox-objekt til query-parameter (se #42 for eksempel på generert url ut av boksen).

Dette må i dag patches inn ved å legge til en override på BoundingBox-klassen:
```
        public override string ToString()
        {
            return $"({string.Join(',', this.Ll)},{string.Join(',', this.Ur)})";
        }
```
Samt endre serialiseringen av query-parameteret i GetDatasetFeaturesAsync til 
```
            if (bbox != null) 
            {
                urlBuilder_.Append(System.Uri.EscapeDataString("bbox") + "=").Append(ConvertToString(bbox, System.Globalization.CultureInfo.InvariantCulture)).Append("&");
            }
```

**Comment by jarped** [comment]
https://github.com/RicoSuter/NSwag/issues/1451

**Comment by jarped** [comment]
https://github.com/RicoSuter/NSwag/issues/1091

**Comment by meastp** [comment]
Denne er nå rettet i branchen meastp_fix_examples.

Jeg har testet med `?bbox=354485.38,7192758.9900000002,374086.83000000002,7208246.9800000004&limit=10` nå (mot Azure-miljøet), og det fungerte fint.

**Comment by larsop** [comment]
Når merges denne inn i master ?

**Comment by larsop** [comment]
Da antar jeg fiksen også løse  denne feilen 

`Error while extracting response for type [class ngis.openapi.client.client.model.Dataset] and content type [application/vnd.kartverket.ngis.dataset+json;version=1.0]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `ngis.openapi.client.client.model.BoundingBox<java.math.BigDecimal>` from Object value (token `JsonToken.START_OBJECT`); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `ngis.openapi.client.client.model.BoundingBox<java.math.BigDecimal>` from Object value (token `JsonToken.START_OBJECT`)(..)
`
som jeg for når bruker 

`metadataApi.getDatasetMetadata(xClientProductVersion, ds.getId(), crsEPSG, normalizedForVisualization );
`

**Comment by larsop** [comment]
Det er ikke så lenge siden jeg hentet ned siste spevc men hentet ned siste open.yml nå testet med swagger-codegen-cli-3.0.34.jar forsatt samme problem.

`Error while extracting response for type [class ngis.openapi.client.client.model.Dataset] and content type [application/vnd.kartverket.ngis.dataset+json;version=1.0]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `ngis.openapi.client.client.model.BoundingBox<java.math.BigDecimal>` from Object value (token `JsonToken.START_OBJECT`); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `ngis.openapi.client.client.model.BoundingBox<java.math.BigDecimal>` from Object value (token `JsonToken.START_OBJECT`)(..)
`
Jeg tester mot kartverket sin test server.

**Comment by meastp** [comment]
Det er litt pussig, så vidt jeg har skjønt har ikke andre biblioteker som genererer tilsvarende problem...?

**Comment by larsop** [comment]
Betyr et at ingen andre bruker swagger-codegen ?

Eller er må man endre koden etter at den er generert som indikert over.

Jeg finner BoundingBox, men ikke  GetDatasetFeaturesAsync

Jeg bruker codegen på denne måten.

java -jar ./src/bin/swagger-codegen-cli-3.0.34.jar generate \
  -i src/main/resources/openapi.yaml \
  --api-package ngis.openapi.client.client.api \
  --model-package ngis.openapi.client.client.model \
  --invoker-package ngis.openapi.client.client.invoker \
  --group-id nibio.no \
  --artifact-id ngis-openapi-api-client \
  --artifact-version 0.0.1-SNAPSHOT \
  -l java \
  --library resttemplate \
  -o ngis-openapi-api-client

**Comment by meastp** [comment]
forsøk med denne i stedet? https://github.com/OpenAPITools/openapi-generator

**Comment by larsop** [comment]
Test med denne, men det funker  dårlig.

java -jar ./src/bin/openapi-generator-cli-6.0.0.jar generate   -i src/main/resources/openapi.yaml   --api-package ngis.openapi.client.client.api   --model-package ngis.openapi.client.client.model   --invoker-package ngis.openapi.client.client.invoker   --group-id no.nibio   --artifact-id ngis-openapi-api-client   --artifact-version 0.0.1-SNAPSHOT   -g java   --library resttemplate   -o ngis-openapi-api-client

Da blir metoden getDatasetFeatures borte og det finnes ikke spor etter BoundingBox.java i den generete koden.

Det er en fordel om det funker med swagger-codegen-cli-3.0.34.jar for det jo også et nokså mye bruke verktøy.

Kanskje også legge inn noen komentarer in yaml fila hvilke verktøy som det funker med.

**Comment by meastp** [comment]
@larsop Jeg har ikke funnet ut hva som ikke følger openapi 3-spesifikasjonen i openapi.yaml. Det må være feil i genereringsverktøyet, eller ser du noe som ikke stemmer med standarden?

**Comment by meastp** [comment]
lukker denne, åpne på nytt hvis mer info
