### ISSUE TITLE
feil json i singleArc

### ISSUE THREAD

**Issue by eirikm** [kartverket/NGIS-OpenAPI#58]
response for json/singleArc er den samme som for singleLineString og stemmer ikke overens med beskrivelsen om is_arc=true

**Comment by meastp** [comment]
Kan du gi et eksempel, gjerne et bestemt kall, slik at det blir enkelt å gjenprodusere feilen og verifisere?

**Comment by eirikm** [comment]
https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/openapi.yaml&nocors#operation/getDatasetFeatures

content-type: json
example: singleArc

den faktiske json i eksempelet samsvarer ikke med beskrivelsen

Dette skyldes:
https://github.com/kartverket/SFKB-API/blob/master/spec/openapi.yaml#L267

**Comment by meastp** [comment]
Se PR #59 - der har jeg lagt inn eksempel på bue (med en retting av beskrivelsen som var feil).

Er det ok?
