### ISSUE TITLE
GET /datasets/<datasetid>/locks - Mulighet for å se andres låser, ikke kun egne låser?

### ISSUE THREAD

**Issue by meastp** [kartverket/NGIS-OpenAPI#71]
TODO

**Comment by larseggan** [comment]
Det er nok lurt ja

**Comment by meastp** [comment]
Jeg tenker meg en ny Content-Type, som angis i Accept-headeren: `application/vnd.kartverket.ngis.locks+json` er eneste i dag, men legger til mulighet for å angi `application/vnd.kartverket.ngis.all_locks+json`?

Fordelen med å benytte Accept/Content-Type er at vi stort sett slipper å endre api/url og at det er lettere å gjøre tillegg/endringer i fremtiden uten at det påvirker eksisterende klienter.

**Comment by larseggan** [comment]
Enig, det bør kunne fungere greit.

**Comment by meastp** [comment]
Implementert med accept / media-type ...all_locks i GET /datasets/{datasetId}/locks. Se dok.
